# Use the official Python 3 image as the base image for the backend
FROM python:3

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container and install dependencies
COPY backend .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django code into the container
# COPY backend .

# Expose the backend port
EXPOSE 8000

# Start the Django server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]